#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^wallet' NEWS | head -1 | cut -d' ' -f2`
for doc in client/wallet client/wallet-rekey ; do
    pod2man --release="$version" --center=wallet \
        --name=`basename "$doc" | tr a-z A-Z` "$doc".pod > "$doc".1
done
for doc in contrib/wallet-summary contrib/wallet-unknown-hosts \
           server/keytab-backend server/wallet-admin server/wallet-backend \
           server/wallet-report ; do
    pod2man --release="$version" --center=wallet --section=8 \
        --name=`basename "$doc" | tr a-z A-Z` "$doc" > "$doc".8
done
