#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^wallet' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center=wallet client/wallet.pod \
    > client/wallet.1
pod2man --release="$version" --center=wallet -s 8 contrib/wallet-summary \
    > contrib/wallet-summary.8
pod2man --release="$version" --center=wallet -s 8 server/keytab-backend \
    > server/keytab-backend.8
pod2man --release="$version" --center=wallet -s 8 server/wallet-admin \
    > server/wallet-admin.8
pod2man --release="$version" --center=wallet -s 8 server/wallet-backend \
    > server/wallet-backend.8
pod2man --release="$version" --center=wallet -s 8 server/wallet-report \
    > server/wallet-report.8
