#!/usr/bin/perl
#
# Test POD formatting for client documentation.
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2008, 2010 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use Test::More;

my @files = qw(wallet.pod);
my $total = scalar (@files);
plan tests => $total;

eval 'use Test::Pod 1.00';
SKIP: {
    skip $total, 'Test::Pod 1.00 required for testing POD' if $@;
    for my $file (@files) {
        pod_file_ok ("$ENV{SOURCE}/../client/$file", "client/$file");
    }
}
