#!/usr/bin/perl -w
#
# Test POD formatting for documentation.
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2008, 2010 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use strict;
use Test::More;
eval 'use Test::Pod 1.00';
plan skip_all => 'Test::Pod 1.00 required for testing POD' if $@;

my @files = qw(client/wallet.pod server/keytab-backend server/wallet-admin
               server/wallet-backend server/wallet-report);
my $total = scalar (@files);
plan tests => $total;
for my $file (@files) {
    pod_file_ok ("$ENV{SOURCE}/../$file", $file);
}
