#!/bin/sh
# $Id$
#
# This is a fake wallet backend that returns bogus data for verification by
# the client test suite.  It doesn't test any of the wallet server code.

command="$1"
shift
type="$1"
if [ "$1" != "keytab" ] ; then
    echo "Unknown object type $1" >&2
    exit 1
fi
shift
if [ -n "$2" ] ; then
    echo "Too many arguments" >&2
    exit 1
fi

case "$command" in
get)
    case "$1" in
    service/fake-test)
        cat data/fake-data
        exit 0
        ;;
    service/fake-srvtab)
        cat data/fake-keytab
        exit 0
        ;;
    *)
        echo "Unknown keytab $1" >&2
        exit 1
        ;;
    esac
    ;;
show)
    if [ "$1" = "service/fake-test" ] ; then
        echo "Some stuff about $1"
        exit 0
    else
        echo "Unknown keytab $1" >&2
        exit 1
    fi
    ;;
expires)
    echo "Expiration date of $1"
    exit 0
    ;;
*)
    echo "Unknown command $command" >&2
    exit 1
    ;;
esac
