#!/bin/sh
#
# Wrapper around the standard wallet-backend script that sets the Perl INC
# path and the WALLET_CONFIG environment variable appropriately.

WALLET_CONFIG="$SOURCE/data/wallet.conf"
export WALLET_CONFIG
exec perl -I"$SOURCE/../perl/lib" "$SOURCE/../server/wallet-backend" -q "$@"
