#!/usr/bin/perl -w
#
# Fake kadmin.local used to test the keytab backend.
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2007
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

unless ($ARGV[0] eq '-q' && @ARGV == 2) {
    die "invalid arguments\n";
}
my @command = split (' ', $ARGV[1]);
unless ("@command[0,1,3,4]" eq 'ktadd -k -q -norandkey') {
    die "invalid command @command\n";
}
if ($command[5] eq 'error@EXAMPLE.ORG') {
    warn "Some bad stuff\n";
    exit 1;
}
open (OUT, '>', $command[2]) or die "cannot create $command[2]: $!\n";
print OUT $command[5], "\n";
close OUT;
exit 0;
